### ISSUE TITLE
suggestion: newer dotnet support.

### ISSUE THREAD

**Issue by litecave** [Folleach/GeometryDashAPI#13]
мне кажется это нужно

**Comment by Folleach** [comment]
The library [has](https://github.com/Folleach/GeometryDashAPI/blob/master/GeometryDashAPI/GeometryDashAPI.csproj#L4) target .net standard 2.1 (latest for 12 june 2022).  
It's compatible for most newest .net versions and has minimal dependence on the "platform" (Mono, .net core)  
[Microsoft doc](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1)

Do you have a more specific problem or suggestion?

**Comment by Folleach** [comment]
Sorry for my long answer :(

**Comment by Folleach** [comment]
For example. I use this library for .net 6 project. It's latest version of all dotnet :)  
But .net 7 is waiting for us soon and the library will also work on it
