### ISSUE TITLE
Can't download on NuGet

### ISSUE THREAD

**Issue by Necrosis000** [Folleach/GeometryDashAPI#15]
**Describe the bug**
I can't download the library on NuGet it just returns this in the console:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'GeometryDashAPI 0.1.16'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

**To Reproduce**
1. Try downloading it

**Expected behavior**
I expected to have the program downloaded

**Additional context**
Nothing  really

**Comment by Folleach** [comment]
Are you using .NET Framework v4.7.2? This library targeting [only on netstandard 2.1](https://github.com/Folleach/GeometryDashAPI/blob/master/GeometryDashAPI/GeometryDashAPI.csproj#L4), it's standard version is not compabile with any .net framework versions: https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

I recommend use net core 3.0+ or .net 5+

Also I think it's possible to targeting on netstandard 2.0 too, if you need it only on framework

**Comment by Necrosis000** [comment]
by chance how would you get it to work for netstandard 2.0?

**Comment by Folleach** [comment]
Done. Since `0.1.17` this library can work on net framework 4.6.1 or higher.

![image](https://user-images.githubusercontent.com/32067915/221346910-85f4563d-82c7-4d02-ae00-d29d59bd5032.png)
