### ISSUE TITLE
Is there a documentation for GeometryDashAPI?

### ISSUE THREAD

**Issue by ptbdev** [Folleach/GeometryDashAPI#23]
2nd post here, I'm just curious if there is an official documentation somewhere of your GeometryDashAPI. Please let me know if there is one :)

**Comment by Folleach** [comment]
Hello, there is no good documentation now  
I'm planning to add documentation with release `0.2`, which is being prepared now

As an alternative you can see basic [Examples](https://github.com/Folleach/GeometryDashAPI/tree/master/Examples) and for combination some parts of data use a IntelliSense...
You can also ask questions here or in my discord Folleach#8437

If you interested in `0.2`, you can see [dev](https://github.com/Folleach/GeometryDashAPI/tree/dev) branch, there are points that will go into the documentation

**Comment by ptbdev** [comment]
Thanks for your quick response! :0

Definitely looking forward to 0.2. Fyi I actually did look at Examples and all the code works fine for me except for one thing. GetLevelByName("level_name") is apparently an obsolete method, and I get a warning telling me to use GetLevel("level_name", revision) instead. I don't know what the 2nd parameter is supposed to mean. Could you explain? Thx

**Comment by Folleach** [comment]
Yes, it is :)

Or just call `local.GetLevel("Test")` it is equivalent of `local.GetLevel("Test", 0)` if you don't want to care about revisions

Also you can enumerable all levels with
```cs
var local = new LocalLevels();
foreach (var levelInfo in local)
{
    var level = new Level(levelInfo.LevelString, compressed: true);
    var moves = level.Blocks.Cast<MoveTrigger>().ToArray();
}
```

**Comment by Folleach** [comment]
Documentation work in progress in [wiki](https://github.com/Folleach/GeometryDashAPI/wiki)  
Links to the topics can be found in the [readme](https://github.com/Folleach/GeometryDashAPI)
