### ISSUE TITLE
Opening official levels

### ISSUE THREAD

**Issue by MonsterDruide1** [Folleach/GeometryDashAPI#3]
In the `Resources`-directory of GeometryDash (not the Appdata, the actual installation dir) there is the `LevelData.plist` file. It probably contains the official levels within Geometry Dash, so I'd like to open those in the API.

**Comment by Folleach** [comment]
I will think about this.
But, I already saw it. And it caused a problem to understand it.

**Comment by MonsterDruide1** [comment]
I already tried to parse it with the methods from normal levels, but Base64 fails because of either wrong characters or wrong padding characters. Fixing the missing second "="-sign will fail the GZipDecompress method...

**Comment by Folleach** [comment]
Released in [v0.2.8](https://www.nuget.org/packages/GeometryDashAPI/0.2.8)
