### ISSUE TITLE
Edit SFX and Edit Music Object Support

### ISSUE THREAD

**Issue by guighub** [Folleach/GeometryDashAPI#31]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a MIDI importer for Geometry Dash that imports each note as a sound effect with a set pitch and volume, and I need a way to stop the note with an "Edit SFX" object after the MIDI note ends.

**Describe the solution you'd like**
Edit Music and Edit SFX objects similar to the `SfxTrigger()` object in the current API.

**Describe alternatives you've considered**
I tried toggling the SFX object on or off with a Toggle trigger object but I don't think it affects the sound.

**Additional context**
No additional context that I know of.

**Comment by Folleach** [comment]
Thank you for request.
I'll go add Edit Song Trigger (that's what it's called in the game) and Edit Sfx Trigger

> I tried toggling the SFX object on or off with a Toggle trigger object but I don't think it affects the sound.
You're right, toggle trigger is just used to activate some trigger, no more

**Comment by Folleach** [comment]
I've done :)  
Released in `v0.2.23`

Your project is interesting.  
I'd like to take a look at your project, when you're done, will you share it?

**Comment by ascpixi** [comment]
@Folleach Hi! I'm also interested in SFX trigger functionality. It seems like the SFXGroup member is missing from [SfxTrigger](https://github.com/Folleach/GeometryDashAPI/blob/v0.2.23/GeometryDashAPI/Levels/GameObjects/Triggers/SfxTrigger.cs). It is present in [EditSfxTrigger](https://github.com/Folleach/GeometryDashAPI/blob/2733ee9b259d51866f43b9c868e3538158d573c1/GeometryDashAPI/Levels/GameObjects/Triggers/EditSfxTrigger.cs#L34), so I'm not sure if this is an oversight. Thanks!

![image](https://github.com/Folleach/GeometryDashAPI/assets/44982772/b5755f0c-4cba-4c22-92c7-5d7fab62aad1)

**Comment by guighub** [comment]
> I've done :) [EditSfxTrigger](https://github.com/Folleach/GeometryDashAPI/blob/v0.2.23/GeometryDashAPI/Levels/GameObjects/Triggers/EditSfxTrigger.cs) and [EditSongTrigger](https://github.com/Folleach/GeometryDashAPI/blob/v0.2.23/GeometryDashAPI/Levels/GameObjects/Triggers/EditSongTrigger.cs) released in [v0.2.23](https://github.com/Folleach/GeometryDashAPI/releases/tag/v0.2.23)
> 
> Your project is interesting. I'd like to take a look at your project, when you're done, will you share it?

Thank you so much! And yes, when the project is mostly complete I plan to make a repo for it.

**Comment by ascpixi** [comment]
> @Folleach Hi! I'm also interested in SFX trigger functionality. It seems like the SFXGroup member is missing from [SfxTrigger](https://github.com/Folleach/GeometryDashAPI/blob/v0.2.23/GeometryDashAPI/Levels/GameObjects/Triggers/SfxTrigger.cs). It is present in [EditSfxTrigger](https://github.com/Folleach/GeometryDashAPI/blob/2733ee9b259d51866f43b9c868e3538158d573c1/GeometryDashAPI/Levels/GameObjects/Triggers/EditSfxTrigger.cs#L34), so I'm not sure if this is an oversight. Thanks in advance!

I have implemented this in pull request #32. @Folleach

**Comment by Folleach** [comment]
@ascpixi oh... Wow. Thank you! I didn't notice that the trigger has other pages at first, hah

I've review and merge your pull request #32  
Now I should add other missing properties, then I'll create a new release

**Comment by Folleach** [comment]
So, it seems I've added properties from all pages.
You can use it in the version [0.2.24](https://github.com/Folleach/GeometryDashAPI/releases/tag/v0.2.24)

Thank you very much! Have a good day ^_^  
If you have any more questions, feel free to ask
